Remove style foe show command

diff --git a/bin/sote b/bin/sote
--- a/bin/sote
+++ b/bin/sote
@@ -48,7 +48,7 @@ sote() {
 
     # sote vars
 
-    local version=0.1.3
+    local version=0.1.4
     local store="$SOTE_STORE"
 
     # reset colors
@@ -167,9 +167,9 @@ sote() {
             path=$( git config --file $store --get "store.$name" )
             if [ "$path" != "" ]
             then
-                echo -e "${C}$name ${Y}› ${NONE}$path${NONE}"
+                echo -e "$path"
             else
-                echo -e "${EMR}error: ${NONE}no entry for ${C}$name${NONE}"
+                echo -e "${EMR}error: ${NONE}no entry for ${C}$name${NONE}"; exit 1
             fi
             return;
             ;;
